place1 = input("Enter the location1: ")
name = input("Enter name: ")
adjective1 = input("Adjective1: ")
adjective2 = input("Adjective2: ")
adjective3 = input("Adjective3: ")
place2 = input("Enter the location2: ")
food = input("Enter food: ")
verb = input("Enter verb: ")
print(end="*" * 5)
print()

print(f"Yesterday, I went to {place1}")
print(f"There I met {name}.")
print(f"I was very {adjective1} because we had some plans.")
print(f"We went {verb}ing and it was really {adjective2}.")
print(f"{name} even took me to lunch at a {place2} where we ate some {food}.")
print(f"Overall, it was a {adjective3} day.")